# Generated by Django 5.0 on 2023-12-28 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=200)),
                ('peso_atual', models.FloatField()),
                ('medicamento_atual', models.TextField(blank=True)),
                ('receita', models.TextField(blank=True)),
                ('exames', models.TextField(blank=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pet')),
            ],
        ),
    ]
